2020-08-26 12:38:17.787 [error] <0.558.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 12:38:17.791 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 12:47:49.012 [error] <0.574.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 CRASH REPORT Process <0.574.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40
2020-08-26 12:47:49.012 [error] <0.558.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 12:47:49.012 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 12:48:40.461 [error] <0.421.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 CRASH REPORT Process <0.421.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40
2020-08-26 12:48:40.461 [error] <0.405.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 12:48:40.464 [error] <0.402.0> CRASH REPORT Process <0.402.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 13:07:51.484 [error] <0.574.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 CRASH REPORT Process <0.574.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40
2020-08-26 13:07:51.486 [error] <0.558.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 13:07:51.486 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 14:56:58.163 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 14:56:58.169 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 14:56:58.178 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 14:56:58.185 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 14:56:58.211 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 14:56:58.249 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 14:56:58.260 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 14:56:58.270 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 14:56:58.296 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 14:56:58.307 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 14:56:58.455 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 14:56:58.455 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 14:56:58.521 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 14:56:58.526 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 14:56:58.540 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 14:56:58.569 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 14:56:58.569 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 14:56:58.576 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 14:56:58.643 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 14:56:58.652 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 14:56:58.662 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 14:56:58.668 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 14:56:58.680 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 14:56:58.686 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 14:56:58.703 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 14:56:58.736 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 14:56:58.881 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 14:56:58.881 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 14:56:58.884 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 14:56:58.944 [error] <0.699.0> gen_server <0.699.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.950 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.951 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.699.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.951 [error] <0.707.0> gen_server <0.707.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.951 [error] <0.707.0> CRASH REPORT Process <0.707.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.952 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.707.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.952 [error] <0.708.0> gen_server <0.708.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.952 [error] <0.708.0> CRASH REPORT Process <0.708.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.952 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.708.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.953 [error] <0.709.0> gen_server <0.709.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.953 [error] <0.709.0> CRASH REPORT Process <0.709.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.953 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.709.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.953 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.709.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:58.954 [error] <0.696.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16760>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.697.0> exit with reason killed in context child_terminated
2020-08-26 14:56:58.954 [error] <0.696.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16760>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.697.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.117 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.696.0> exit with reason shutdown in context child_terminated
2020-08-26 14:56:59.119 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 14:56:59.119 [error] <0.834.0> gen_server <0.834.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.122 [error] <0.834.0> CRASH REPORT Process <0.834.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.122 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.834.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.122 [error] <0.835.0> gen_server <0.835.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.123 [error] <0.835.0> CRASH REPORT Process <0.835.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.123 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.835.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.123 [error] <0.836.0> gen_server <0.836.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.123 [error] <0.836.0> CRASH REPORT Process <0.836.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.124 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.836.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.124 [error] <0.837.0> gen_server <0.837.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.124 [error] <0.837.0> CRASH REPORT Process <0.837.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.125 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.837.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.125 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.837.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.126 [error] <0.831.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399426.15257>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.832.0> exit with reason killed in context child_terminated
2020-08-26 14:56:59.126 [error] <0.831.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399426.15257>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.832.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.126 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.831.0> exit with reason shutdown in context child_terminated
2020-08-26 14:56:59.126 [error] <0.841.0> gen_server <0.841.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.126 [error] <0.841.0> CRASH REPORT Process <0.841.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.127 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.841.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.127 [error] <0.842.0> gen_server <0.842.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.128 [error] <0.842.0> CRASH REPORT Process <0.842.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.128 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.842.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.128 [error] <0.843.0> gen_server <0.843.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.129 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.131 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.843.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.131 [error] <0.844.0> gen_server <0.844.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.131 [error] <0.844.0> CRASH REPORT Process <0.844.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.132 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.844.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.132 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.844.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.132 [error] <0.838.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16909>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.839.0> exit with reason killed in context child_terminated
2020-08-26 14:56:59.133 [error] <0.838.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16909>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.839.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.133 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.838.0> exit with reason shutdown in context child_terminated
2020-08-26 14:56:59.133 [error] <0.848.0> gen_server <0.848.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.133 [error] <0.848.0> CRASH REPORT Process <0.848.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.134 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.848.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.134 [error] <0.849.0> gen_server <0.849.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.135 [error] <0.849.0> CRASH REPORT Process <0.849.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.135 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.849.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.135 [error] <0.850.0> gen_server <0.850.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.136 [error] <0.850.0> CRASH REPORT Process <0.850.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.136 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.850.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.136 [error] <0.851.0> gen_server <0.851.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.137 [error] <0.851.0> CRASH REPORT Process <0.851.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.137 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.851.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.137 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.851.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.137 [error] <0.845.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16931>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.846.0> exit with reason killed in context child_terminated
2020-08-26 14:56:59.138 [error] <0.845.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16931>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.846.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.138 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.845.0> exit with reason shutdown in context child_terminated
2020-08-26 14:57:00.120 [warning] <0.588.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2020-08-26 14:57:36.948 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 14:57:36.952 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 14:57:36.959 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 14:57:36.967 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 14:57:36.984 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 14:57:37.029 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 14:57:37.036 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 14:57:37.041 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 14:57:37.056 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 14:57:37.066 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 14:57:37.119 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 14:57:37.120 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 14:57:37.127 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 14:57:37.130 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 14:57:37.148 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 14:57:37.154 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 14:57:37.155 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 14:57:37.156 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 14:57:37.172 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 14:57:37.188 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 14:57:37.197 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 14:57:37.199 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 14:57:37.205 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 14:57:37.208 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 14:57:37.219 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 14:57:37.241 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 14:57:37.339 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 14:57:37.339 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 14:57:37.342 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 14:57:37.427 [error] <0.478.0> gen_server <0.478.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.449 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.449 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.478.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.449 [error] <0.486.0> gen_server <0.486.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.450 [error] <0.486.0> CRASH REPORT Process <0.486.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.451 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.486.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.451 [error] <0.487.0> gen_server <0.487.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.452 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.452 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.487.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.452 [error] <0.488.0> gen_server <0.488.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.452 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.452 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.488.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.453 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.488.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:57:37.453 [error] <0.475.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.4281642551.1066008577.21288>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.476.0> exit with reason killed in context child_terminated
2020-08-26 14:57:37.453 [error] <0.475.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.4281642551.1066008577.21288>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.476.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:57:37.524 [error] <0.474.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.475.0> exit with reason shutdown in context child_terminated
2020-08-26 14:57:37.525 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 14:57:37.525 [error] <0.613.0> gen_server <0.613.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.526 [error] <0.613.0> CRASH REPORT Process <0.613.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.526 [error] <0.612.0> Supervisor {<0.612.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.611.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.611.0>, #Ref<0.4281642551.1066008577.21594>) at <0.613.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.527 [error] <0.614.0> gen_server <0.614.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.527 [error] <0.614.0> CRASH REPORT Process <0.614.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.529 [error] <0.612.0> Supervisor {<0.612.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.611.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.611.0>, #Ref<0.4281642551.1066008577.21594>) at <0.614.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.529 [error] <0.615.0> gen_server <0.615.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.529 [error] <0.615.0> CRASH REPORT Process <0.615.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.529 [error] <0.612.0> Supervisor {<0.612.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.611.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.611.0>, #Ref<0.4281642551.1066008577.21594>) at <0.615.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:38.511 [warning] <0.367.0> lager_error_logger_h dropped 54 messages in the last second that exceeded the limit of 50 messages/sec
2020-08-26 14:59:01.425 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 14:59:01.435 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 14:59:01.517 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 14:59:01.523 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 14:59:01.548 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 14:59:01.582 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 14:59:01.591 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 14:59:01.597 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 14:59:01.620 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 14:59:01.624 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 14:59:01.685 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 14:59:01.685 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 14:59:01.695 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 14:59:01.700 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 14:59:01.726 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 14:59:01.734 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 14:59:01.734 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 14:59:01.737 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 14:59:01.751 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 14:59:01.771 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 14:59:01.784 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 14:59:01.788 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 14:59:01.791 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 14:59:01.797 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 14:59:01.813 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 14:59:01.878 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 14:59:02.024 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 14:59:02.024 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 14:59:02.028 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 14:59:02.137 [error] <0.488.0> gen_server <0.488.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.181 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.181 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.488.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.182 [error] <0.496.0> gen_server <0.496.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.182 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.183 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.496.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.183 [error] <0.497.0> gen_server <0.497.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.183 [error] <0.497.0> CRASH REPORT Process <0.497.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.184 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.497.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.184 [error] <0.498.0> gen_server <0.498.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.184 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.184 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.498.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.185 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.498.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.185 [error] <0.485.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750402.152681>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.486.0> exit with reason killed in context child_terminated
2020-08-26 14:59:02.185 [error] <0.485.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750402.152681>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.486.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.361 [error] <0.484.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.485.0> exit with reason shutdown in context child_terminated
2020-08-26 14:59:02.361 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 14:59:02.362 [error] <0.623.0> gen_server <0.623.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.366 [error] <0.623.0> CRASH REPORT Process <0.623.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.369 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.623.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.412 [error] <0.624.0> gen_server <0.624.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.413 [error] <0.624.0> CRASH REPORT Process <0.624.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.414 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.624.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.415 [error] <0.625.0> gen_server <0.625.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.415 [error] <0.625.0> CRASH REPORT Process <0.625.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.415 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.625.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.415 [error] <0.626.0> gen_server <0.626.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.415 [error] <0.626.0> CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.416 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.626.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.416 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.626.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.416 [error] <0.620.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750403.150862>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.621.0> exit with reason killed in context child_terminated
2020-08-26 14:59:02.416 [error] <0.620.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750403.150862>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.621.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.417 [error] <0.484.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.620.0> exit with reason shutdown in context child_terminated
2020-08-26 14:59:02.417 [error] <0.630.0> gen_server <0.630.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.417 [error] <0.630.0> CRASH REPORT Process <0.630.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.417 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.630.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.417 [error] <0.631.0> gen_server <0.631.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.418 [error] <0.631.0> CRASH REPORT Process <0.631.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.418 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.631.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.418 [error] <0.632.0> gen_server <0.632.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.419 [error] <0.632.0> CRASH REPORT Process <0.632.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.419 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.632.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.419 [error] <0.633.0> gen_server <0.633.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.419 [error] <0.633.0> CRASH REPORT Process <0.633.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.420 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.633.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.420 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.633.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.420 [error] <0.627.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750403.150893>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.628.0> exit with reason killed in context child_terminated
2020-08-26 15:00:08.201 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:00:08.206 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:00:08.214 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:00:08.222 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:00:08.260 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:00:08.299 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:00:08.312 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:00:08.327 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:00:08.358 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:00:08.364 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:00:08.419 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:00:08.420 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:00:08.428 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:00:08.431 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:00:08.443 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:00:08.450 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:00:08.452 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:00:08.460 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:00:08.492 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:00:08.503 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:00:08.510 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:00:08.512 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:00:08.515 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:00:08.531 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:00:08.549 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:00:08.583 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:00:08.696 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:00:08.696 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:00:08.699 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:00:08.791 [error] <0.488.0> gen_server <0.488.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:08.818 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:08.819 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.1177299713.2945056769.146320>) at <0.488.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:08.819 [error] <0.496.0> gen_server <0.496.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:08.819 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:08.820 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.1177299713.2945056769.146320>) at <0.496.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:08.820 [error] <0.497.0> gen_server <0.497.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:08.820 [error] <0.497.0> CRASH REPORT Process <0.497.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:49.345 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:00:49.349 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:00:49.358 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:00:49.363 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:00:49.385 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:00:49.423 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:00:49.433 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:00:49.441 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:00:49.461 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:00:49.466 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:00:49.510 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:00:49.510 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:00:49.518 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:00:49.520 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:00:49.531 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:00:49.539 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:00:49.540 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:00:49.543 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:00:49.563 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:00:49.581 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:00:49.594 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:00:49.596 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:00:49.601 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:00:49.613 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:00:49.633 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:00:49.661 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:00:49.760 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:00:49.760 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:00:49.762 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:00:49.832 [error] <0.478.0> gen_server <0.478.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:49.852 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:49.853 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.1098111977.1334181889.170690>) at <0.478.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:49.853 [error] <0.486.0> gen_server <0.486.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:49.853 [error] <0.486.0> CRASH REPORT Process <0.486.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:49.854 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.1098111977.1334181889.170690>) at <0.486.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:49.854 [error] <0.487.0> gen_server <0.487.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:49.854 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:49.855 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.1098111977.1334181889.170690>) at <0.487.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:01:44.946 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:01:44.950 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:01:44.957 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:01:44.968 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:01:44.994 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:01:45.024 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:01:45.032 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:01:45.036 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:01:45.053 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:01:45.060 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:01:45.116 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:01:45.116 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:01:45.123 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:01:45.130 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:01:45.148 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:01:45.156 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:01:45.157 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:01:45.159 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:01:45.182 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:01:45.198 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:01:45.209 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:01:45.212 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:01:45.221 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:01:45.227 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:01:45.241 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:01:45.260 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:01:45.354 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:01:45.354 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:01:45.356 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:01:45.430 [error] <0.477.0> CRASH REPORT Process <0.477.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>} in 'Elixir.Range':new/2 line 63
2020-08-26 15:01:45.430 [error] <0.476.0>@Elixir.DBConnection.ConnectionPool:init:22 CRASH REPORT Process <0.476.0> with 0 neighbours crashed with reason: no match of right hand value {error,{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>},[{'Elixir.Range',new,2,[{file,"lib/range.ex"},{line,63}]},{'Elixir.DBConnection.ConnectionPool.Pool',init,1,[{file,"lib/db_connection/connection_pool/pool.ex"},{line,18}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},...]},...]}} in 'Elixir.DBConnection.ConnectionPool':init/1 line 22
2020-08-26 15:02:46.965 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:02:46.972 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:02:47.013 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:02:47.020 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:02:47.049 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:02:47.090 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:02:47.104 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:02:47.119 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:02:47.142 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:02:47.154 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:02:47.212 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:02:47.212 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:02:47.223 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:02:47.232 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:02:47.265 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:02:47.273 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:02:47.274 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:02:47.276 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:02:47.301 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:02:47.344 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:02:47.350 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:02:47.353 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:02:47.362 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:02:47.368 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:02:47.387 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:02:47.422 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:02:47.562 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:02:47.562 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:02:47.565 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:02:47.635 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>} in 'Elixir.Range':new/2 line 63
2020-08-26 15:02:47.637 [error] <0.485.0>@Elixir.DBConnection.ConnectionPool:init:22 Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.2205629116.2676621313.227754>,opts => [{timeout,15000},{pool_size,<<"10">>},{...}],...}) at undefined exit with reason no match of right hand value {error,{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>},[{'Elixir.Range',new,2,[{file,"lib/range.ex"},{line,63}]},{'Elixir.DBConnection.ConnectionPool.Pool',init,1,[{file,"lib/db_connection/connection_pool/pool.ex"},{line,18}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},...]},...]}} in 'Elixir.DBConnection.ConnectionPool':init/1 line 22 in context start_error
2020-08-26 15:04:08.637 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:04:08.641 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:04:08.648 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:04:08.654 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:04:08.676 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:04:08.707 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:04:08.723 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:04:08.733 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:04:08.763 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:04:08.767 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:04:08.816 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:04:08.816 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:04:08.823 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:04:08.826 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:04:08.843 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:04:08.848 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:04:08.849 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:04:08.850 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:04:08.860 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:04:08.873 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:04:08.881 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:04:08.883 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:04:08.885 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:04:08.889 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:04:08.895 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:04:08.913 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:04:09.032 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:04:09.032 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:04:09.034 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:04:09.096 [error] <0.477.0> CRASH REPORT Process <0.477.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>} in 'Elixir.Range':new/2 line 63
2020-08-26 15:04:44.291 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:04:44.296 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:04:44.303 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:04:44.308 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:04:44.331 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:04:44.358 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:04:44.374 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:04:44.378 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:04:44.410 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:04:44.426 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:04:44.485 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:04:44.485 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:04:44.494 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:04:44.499 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:04:44.531 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:04:44.536 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:04:44.536 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:04:44.538 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:04:44.553 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:04:44.579 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:04:44.585 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:04:44.587 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:04:44.590 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:04:44.594 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:04:44.604 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:04:44.621 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:04:44.739 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:04:44.739 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:04:44.741 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:04:44.873 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 15:05:16.632 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ef14a242-bcb9-41d5-89bb-6e398cee8b24">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...},...}
2020-08-26 15:05:16.654 [error] <0.843.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ef14a242-bcb9-41d5-89bb-6e398cee8b24">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api..."},...]},...]},...},...}
2020-08-26 15:11:06.852 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:11:06.857 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:11:06.866 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:11:06.872 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:11:06.895 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:11:06.926 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:11:06.934 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:11:06.938 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:11:06.961 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:11:06.965 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:11:07.016 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:11:07.017 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:11:07.027 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:11:07.033 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:11:07.059 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:11:07.063 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:11:07.063 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:11:07.065 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:11:07.078 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:11:07.099 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:11:07.112 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:11:07.117 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:11:07.127 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:11:07.138 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:11:07.154 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:11:07.182 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:11:07.279 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:11:07.279 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:11:07.282 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:11:07.515 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 15:11:16.185 [error] <0.622.0> CRASH REPORT Process <0.622.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"23e4301c-e590-4d63-8b47-f247f4233128">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...},...}
2020-08-26 15:11:16.217 [error] <0.622.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"23e4301c-e590-4d63-8b47-f247f4233128">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api..."},...]},...]},...},...}
2020-08-26 15:12:01.004 [error] <0.624.0> CRASH REPORT Process <0.624.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ebac76e2-6617-4c16-864c-b9e8b8f67b53">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...},...}
2020-08-26 15:12:01.005 [error] <0.624.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ebac76e2-6617-4c16-864c-b9e8b8f67b53">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api..."},...]},...]},...},...}
2020-08-26 15:14:07.163 [error] <0.680.0> CRASH REPORT Process <0.680.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"b24f959c-6d87-45ba-b401-94d49de9b03b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:14:07.166 [error] <0.680.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"b24f959c-6d87-45ba-b401-94d49de9b03b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:14:52.131 [error] <0.743.0> CRASH REPORT Process <0.743.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"fc036d9f-0616-4e10-a2d6-13f5968b8f2b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:14:52.135 [error] <0.743.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"fc036d9f-0616-4e10-a2d6-13f5968b8f2b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:15:24.936 [error] <0.802.0> CRASH REPORT Process <0.802.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"8b88647a-3ec1-4b9c-a670-0384fb1462b7">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:15:24.937 [error] <0.802.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"8b88647a-3ec1-4b9c-a670-0384fb1462b7">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:16:13.763 [error] <0.804.0> CRASH REPORT Process <0.804.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:16:13.768 [error] <0.804.0> Cowboy stream 4 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:18:30.063 [error] <0.864.0> CRASH REPORT Process <0.864.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"ef09f4c2-51fe-4387-beb1-e68a7ef9268c">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...},...}
2020-08-26 15:18:30.063 [error] <0.864.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.863.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"ef09f4c2-51fe-4387-beb1-e68a7ef9268c">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...}
2020-08-26 15:18:48.600 [error] <0.927.0> CRASH REPORT Process <0.927.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"c6a6c0d9-21f2-4d7f-9d1c-f2cfb26a1c6a">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...},...}
2020-08-26 15:18:48.600 [error] <0.927.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.863.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"c6a6c0d9-21f2-4d7f-9d1c-f2cfb26a1c6a">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...}
2020-08-26 15:19:36.232 [error] <0.930.0> CRASH REPORT Process <0.930.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"94823f86-2abd-4f18-83e1-6172df779089">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...},...}
2020-08-26 15:19:36.232 [error] <0.930.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.863.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"94823f86-2abd-4f18-83e1-6172df779089">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...}
2020-08-26 15:24:00.678 [error] <0.1005.0> CRASH REPORT Process <0.1005.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"a12a01dd-de01-460e-8ff0-40400ce007b2">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:24:00.680 [error] <0.1005.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.987.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"a12a01dd-de01-460e-8ff0-40400ce007b2">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:24:43.944 [error] <0.1068.0> CRASH REPORT Process <0.1068.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...},...}
2020-08-26 15:24:43.944 [error] <0.1068.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.987.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...}
2020-08-26 15:26:02.620 [error] <0.1128.0> CRASH REPORT Process <0.1128.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-08-26 15:26:02.620 [error] <0.1128.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1127.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-08-26 15:26:37.695 [error] <0.1182.0> CRASH REPORT Process <0.1182.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...},...}
2020-08-26 15:26:37.695 [error] <0.1182.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1127.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...}
2020-08-26 15:27:09.100 [error] <0.1237.0> CRASH REPORT Process <0.1237.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:27:09.100 [error] <0.1237.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1127.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:33:59.613 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:33:59.618 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:33:59.625 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:33:59.631 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:33:59.662 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:33:59.699 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:33:59.709 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:33:59.714 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:33:59.737 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:33:59.751 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:33:59.815 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:33:59.815 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:33:59.824 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:33:59.827 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:33:59.837 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:33:59.863 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:33:59.864 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:33:59.869 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:33:59.899 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:33:59.919 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:33:59.928 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:33:59.931 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:33:59.942 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:33:59.958 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:33:59.975 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:34:00.031 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:34:00.132 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:34:00.132 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:34:00.134 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:34:00.328 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 15:35:42.904 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 75206,message => nil,postgres => #{code => undefined_table,file => <<"parse_relation.c">>,line => <<"1194">>,message => <<"relation \"users\" does not exist">>,pg_code => <<"42P01">>,position => <<"13">>,routine => <<"parserOpenTable">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"INSERT INTO \"users\" (\"email\",\"inserted_at\",\"updated_at\",\"id\") VALUES ($1,$2,$3,$4)">>},[{'Elixir.Ecto.Adapters.SQL',...},...]},...},...},...}
2020-08-26 15:35:42.941 [error] <0.649.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 75206,message => nil,postgres => #{code => undefined_table,file => <<"parse_relation.c">>,line => <<"1194">>,message => <<"relation \"users\" does not exist">>,pg_code => <<"42P01">>,position => <<"13">>,routine => <<"parserOpenTable">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"INSERT INTO \"users\" (\"email\",\"inserted_at\",\"updated_at\",\"id\") VALUES ($1,$2,$3,$4)">>},[{'Elixir.Ecto.Adapters.SQL',...},...]},...},...}
2020-08-26 15:38:06.299 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:38:06.305 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:38:06.314 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:38:06.326 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:38:06.361 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:38:06.408 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:38:06.434 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:38:06.437 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:38:06.449 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:38:06.457 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:38:06.511 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:38:06.512 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:38:06.520 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:38:06.524 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:38:06.534 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:38:06.542 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:38:06.543 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:38:06.549 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:38:06.575 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:38:06.599 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:38:06.604 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:38:06.606 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:38:06.609 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:38:06.614 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:38:06.624 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:38:06.653 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:38:06.749 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:38:06.749 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:38:06.752 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:38:06.942 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 15:38:14.667 [error] <0.622.0> CRASH REPORT Process <0.622.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:38:14.675 [error] <0.622.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:40:31.195 [error] <0.641.0> CRASH REPORT Process <0.641.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...},...}
2020-08-26 15:40:31.197 [error] <0.641.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.625.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...}
2020-08-26 15:41:51.678 [error] <0.701.0> CRASH REPORT Process <0.701.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:41:51.679 [error] <0.701.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.700.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:42:54.865 [error] <0.761.0> CRASH REPORT Process <0.761.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:42:54.866 [error] <0.761.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:45:48.494 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:45:48.499 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:45:48.506 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:45:48.511 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:45:48.535 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:45:48.570 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:45:48.578 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:45:48.584 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:45:48.603 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:45:48.613 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:45:48.672 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:45:48.672 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:45:48.684 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:45:48.696 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:45:48.715 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:45:48.724 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:45:48.724 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:45:48.727 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:45:48.756 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:45:48.798 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:45:48.809 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:45:48.813 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:45:48.896 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:45:48.937 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:45:48.983 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:45:49.043 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:45:49.193 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:45:49.193 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:45:49.196 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:45:49.351 [info] <0.44.0> Application exchange_api started on node nonode@nohost
2020-08-26 15:46:17.136 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 49,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:46:17.159 [error] <0.843.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 49,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:47:17.841 [error] <0.855.0> CRASH REPORT Process <0.855.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Template.UndefinedError',assigns => #{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 50,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"50">>,<<"content-type">> => <<"application/json">>,<<"hos...">> => ...,...},...}},...},...},...},...},...},...},...}
2020-08-26 15:47:17.842 [error] <0.855.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Template.UndefinedError',assigns => #{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 50,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"50">>,<<"content-type">> => <<"application/json">>,<<"host">> => <<..>>,...},...}},...},...},...},...},...},...}
2020-08-26 15:49:04.295 [error] <0.968.0> CRASH REPORT Process <0.968.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 59,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:49:04.298 [error] <0.968.0> Cowboy stream 5 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 59,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:53:58.153 [info] <0.44.0> Application lager started on node nonode@nohost
2020-08-26 15:53:58.158 [info] <0.44.0> Application elixir_uuid started on node nonode@nohost
2020-08-26 15:53:58.164 [info] <0.44.0> Application typed_struct started on node nonode@nohost
2020-08-26 15:53:58.170 [info] <0.44.0> Application qex started on node nonode@nohost
2020-08-26 15:53:58.197 [info] <0.44.0> Application xmerl started on node nonode@nohost
2020-08-26 15:53:58.229 [info] <0.44.0> Application sasl started on node nonode@nohost
2020-08-26 15:53:58.237 [info] <0.44.0> Application tools started on node nonode@nohost
2020-08-26 15:53:58.241 [info] <0.44.0> Application jsx started on node nonode@nohost
2020-08-26 15:53:58.262 [info] <0.44.0> Application ranch started on node nonode@nohost
2020-08-26 15:53:58.267 [info] <0.44.0> Application recon started on node nonode@nohost
2020-08-26 15:53:58.325 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2020-08-26 15:53:58.325 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2020-08-26 15:53:58.338 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2020-08-26 15:53:58.342 [info] <0.44.0> Application amqp started on node nonode@nohost
2020-08-26 15:53:58.364 [info] <0.44.0> Application poolboy started on node nonode@nohost
2020-08-26 15:53:58.372 [info] <0.44.0> Application poison started on node nonode@nohost
2020-08-26 15:53:58.373 [info] <0.44.0> Application instream started on node nonode@nohost
2020-08-26 15:53:58.380 [info] <0.44.0> Application money started on node nonode@nohost
2020-08-26 15:53:58.406 [info] <0.44.0> Application exchange started on node nonode@nohost
2020-08-26 15:53:58.415 [info] <0.44.0> Application cowlib started on node nonode@nohost
2020-08-26 15:53:58.432 [info] <0.44.0> Application cowboy started on node nonode@nohost
2020-08-26 15:53:58.436 [info] <0.44.0> Application plug_cowboy started on node nonode@nohost
2020-08-26 15:53:58.465 [info] <0.44.0> Application phoenix_live_view started on node nonode@nohost
2020-08-26 15:53:58.495 [info] <0.44.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-08-26 15:53:58.510 [info] <0.44.0> Application file_system started on node nonode@nohost
2020-08-26 15:53:58.560 [info] <0.44.0> Application phoenix_live_reload started on node nonode@nohost
2020-08-26 15:53:58.682 [info] <0.44.0> Application jose started on node nonode@nohost
2020-08-26 15:53:58.682 [info] <0.44.0> Application guardian started on node nonode@nohost
2020-08-26 15:53:58.685 [info] <0.44.0> Application phoenix_ecto started on node nonode@nohost
2020-08-26 15:53:58.816 [info] <0.44.0> Application exchange_api started on node nonode@nohost
