2020-08-26 12:38:17.787 [error] <0.558.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 12:38:17.791 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 12:47:49.012 [error] <0.574.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 CRASH REPORT Process <0.574.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40
2020-08-26 12:47:49.012 [error] <0.558.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 12:47:49.012 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 12:48:40.461 [error] <0.421.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 CRASH REPORT Process <0.421.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40
2020-08-26 12:48:40.461 [error] <0.405.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 12:48:40.464 [error] <0.402.0> CRASH REPORT Process <0.402.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 13:07:51.484 [error] <0.574.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 CRASH REPORT Process <0.574.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40
2020-08-26 13:07:51.486 [error] <0.558.0>@Elixir.Exchange.Adapters.Flux.Orders:get_live_orders:40 Supervisor 'Elixir.Exchange.Supervisor' had child 'AUXLND' started with 'Elixir.Exchange.MatchingEngine':start_link([{ticker,'AUXLND'},{currency,'GBP'},{min_price,1000},{max_price,100000}]) at undefined exit with reason bad argument in call to erlang:apply({error,econnrefused}, results, []) in 'Elixir.Exchange.Adapters.Flux.Orders':get_live_orders/1 line 40 in context start_error
2020-08-26 13:07:51.486 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'AUXLND',{badarg,[{erlang,apply,[{error,econnrefused},results,[]],[]},{'Elixir.Exchange.Adapters.Flux.Orders',get_live_orders,1,[{file,"lib/exchange/adapters/flux/orders.ex"},{line,40}]},{'Elixir.Exchange.Adapters.Flux',get_live_orders,1,[{file,"lib/exchange/adapters/flux.ex"},{line,67}]},{'Elixir.Exchange.MatchingEngine','order_book_restore!',1,[{file,"lib/exchange/matching_engine.ex"},{line,188}]},{'Elixir.Exchange.MatchingEngine',init,1,[{file,"lib/exch..."},...]},...]}}},...} in application_master:init/4 line 138
2020-08-26 14:56:58.944 [error] <0.699.0> gen_server <0.699.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.950 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.951 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.699.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.951 [error] <0.707.0> gen_server <0.707.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.951 [error] <0.707.0> CRASH REPORT Process <0.707.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.952 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.707.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.952 [error] <0.708.0> gen_server <0.708.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.952 [error] <0.708.0> CRASH REPORT Process <0.708.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.952 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.708.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.953 [error] <0.709.0> gen_server <0.709.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:58.953 [error] <0.709.0> CRASH REPORT Process <0.709.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:58.953 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.709.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:58.953 [error] <0.698.0> Supervisor {<0.698.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.697.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.697.0>, #Ref<0.1716086255.2407399425.16761>) at <0.709.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:58.954 [error] <0.696.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16760>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.697.0> exit with reason killed in context child_terminated
2020-08-26 14:56:58.954 [error] <0.696.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16760>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.697.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.117 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.696.0> exit with reason shutdown in context child_terminated
2020-08-26 14:56:59.119 [error] <0.834.0> gen_server <0.834.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.122 [error] <0.834.0> CRASH REPORT Process <0.834.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.122 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.834.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.122 [error] <0.835.0> gen_server <0.835.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.123 [error] <0.835.0> CRASH REPORT Process <0.835.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.123 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.835.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.123 [error] <0.836.0> gen_server <0.836.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.123 [error] <0.836.0> CRASH REPORT Process <0.836.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.124 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.836.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.124 [error] <0.837.0> gen_server <0.837.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.124 [error] <0.837.0> CRASH REPORT Process <0.837.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.125 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.837.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.125 [error] <0.833.0> Supervisor {<0.833.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.832.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.832.0>, #Ref<0.1716086255.2407399426.15258>) at <0.837.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.126 [error] <0.831.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399426.15257>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.832.0> exit with reason killed in context child_terminated
2020-08-26 14:56:59.126 [error] <0.831.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399426.15257>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.832.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.126 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.831.0> exit with reason shutdown in context child_terminated
2020-08-26 14:56:59.126 [error] <0.841.0> gen_server <0.841.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.126 [error] <0.841.0> CRASH REPORT Process <0.841.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.127 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.841.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.127 [error] <0.842.0> gen_server <0.842.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.128 [error] <0.842.0> CRASH REPORT Process <0.842.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.128 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.842.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.128 [error] <0.843.0> gen_server <0.843.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.129 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.131 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.843.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.131 [error] <0.844.0> gen_server <0.844.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.131 [error] <0.844.0> CRASH REPORT Process <0.844.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.132 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.844.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.132 [error] <0.840.0> Supervisor {<0.840.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.839.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.839.0>, #Ref<0.1716086255.2407399425.16910>) at <0.844.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.132 [error] <0.838.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16909>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.839.0> exit with reason killed in context child_terminated
2020-08-26 14:56:59.133 [error] <0.838.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16909>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.839.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.133 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.838.0> exit with reason shutdown in context child_terminated
2020-08-26 14:56:59.133 [error] <0.848.0> gen_server <0.848.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.133 [error] <0.848.0> CRASH REPORT Process <0.848.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.134 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.848.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.134 [error] <0.849.0> gen_server <0.849.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.135 [error] <0.849.0> CRASH REPORT Process <0.849.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.135 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.849.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.135 [error] <0.850.0> gen_server <0.850.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.136 [error] <0.850.0> CRASH REPORT Process <0.850.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.136 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.850.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.136 [error] <0.851.0> gen_server <0.851.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:56:59.137 [error] <0.851.0> CRASH REPORT Process <0.851.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:56:59.137 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.851.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:56:59.137 [error] <0.847.0> Supervisor {<0.847.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.846.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.846.0>, #Ref<0.1716086255.2407399425.16932>) at <0.851.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.137 [error] <0.845.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16931>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.846.0> exit with reason killed in context child_terminated
2020-08-26 14:56:59.138 [error] <0.845.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.1716086255.2407399425.16931>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.846.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:56:59.138 [error] <0.695.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.845.0> exit with reason shutdown in context child_terminated
2020-08-26 14:57:37.427 [error] <0.478.0> gen_server <0.478.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.449 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.449 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.478.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.449 [error] <0.486.0> gen_server <0.486.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.450 [error] <0.486.0> CRASH REPORT Process <0.486.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.451 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.486.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.451 [error] <0.487.0> gen_server <0.487.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.452 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.452 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.487.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.452 [error] <0.488.0> gen_server <0.488.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.452 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.452 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.488.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.453 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.4281642551.1066008577.21289>) at <0.488.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:57:37.453 [error] <0.475.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.4281642551.1066008577.21288>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.476.0> exit with reason killed in context child_terminated
2020-08-26 14:57:37.453 [error] <0.475.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.4281642551.1066008577.21288>,opts => [{timeout,15000},{pool_size,nil},{pool,'Elixir.DBConnection.ConnectionPool'}],...}) at <0.476.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:57:37.524 [error] <0.474.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.475.0> exit with reason shutdown in context child_terminated
2020-08-26 14:57:37.525 [error] <0.613.0> gen_server <0.613.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.526 [error] <0.613.0> CRASH REPORT Process <0.613.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.526 [error] <0.612.0> Supervisor {<0.612.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.611.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.611.0>, #Ref<0.4281642551.1066008577.21594>) at <0.613.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.527 [error] <0.614.0> gen_server <0.614.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.527 [error] <0.614.0> CRASH REPORT Process <0.614.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.529 [error] <0.612.0> Supervisor {<0.612.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.611.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.611.0>, #Ref<0.4281642551.1066008577.21594>) at <0.614.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:57:37.529 [error] <0.615.0> gen_server <0.615.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:57:37.529 [error] <0.615.0> CRASH REPORT Process <0.615.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:57:37.529 [error] <0.612.0> Supervisor {<0.612.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.611.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.611.0>, #Ref<0.4281642551.1066008577.21594>) at <0.615.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.137 [error] <0.488.0> gen_server <0.488.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.181 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.181 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.488.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.182 [error] <0.496.0> gen_server <0.496.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.182 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.183 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.496.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.183 [error] <0.497.0> gen_server <0.497.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.183 [error] <0.497.0> CRASH REPORT Process <0.497.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.184 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.497.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.184 [error] <0.498.0> gen_server <0.498.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.184 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.184 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.498.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.185 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.3264398455.2139750402.152682>) at <0.498.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.185 [error] <0.485.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750402.152681>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.486.0> exit with reason killed in context child_terminated
2020-08-26 14:59:02.185 [error] <0.485.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750402.152681>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.486.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.361 [error] <0.484.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.485.0> exit with reason shutdown in context child_terminated
2020-08-26 14:59:02.362 [error] <0.623.0> gen_server <0.623.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.366 [error] <0.623.0> CRASH REPORT Process <0.623.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.369 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.623.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.412 [error] <0.624.0> gen_server <0.624.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.413 [error] <0.624.0> CRASH REPORT Process <0.624.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.414 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.624.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.415 [error] <0.625.0> gen_server <0.625.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.415 [error] <0.625.0> CRASH REPORT Process <0.625.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.415 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.625.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.415 [error] <0.626.0> gen_server <0.626.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.415 [error] <0.626.0> CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.416 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.626.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.416 [error] <0.622.0> Supervisor {<0.622.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.621.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.621.0>, #Ref<0.3264398455.2139750403.150863>) at <0.626.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.416 [error] <0.620.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750403.150862>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.621.0> exit with reason killed in context child_terminated
2020-08-26 14:59:02.416 [error] <0.620.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750403.150862>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.621.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.417 [error] <0.484.0> Supervisor 'Elixir.ExchangeApi.Supervisor' had child 'Elixir.ExchangeApi.Repo' started with 'Elixir.ExchangeApi.Repo':start_link([]) at <0.620.0> exit with reason shutdown in context child_terminated
2020-08-26 14:59:02.417 [error] <0.630.0> gen_server <0.630.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.417 [error] <0.630.0> CRASH REPORT Process <0.630.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.417 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.630.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.417 [error] <0.631.0> gen_server <0.631.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.418 [error] <0.631.0> CRASH REPORT Process <0.631.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.418 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.631.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.418 [error] <0.632.0> gen_server <0.632.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.419 [error] <0.632.0> CRASH REPORT Process <0.632.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.419 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.632.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.419 [error] <0.633.0> gen_server <0.633.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 14:59:02.419 [error] <0.633.0> CRASH REPORT Process <0.633.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 14:59:02.420 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.633.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 14:59:02.420 [error] <0.629.0> Supervisor {<0.629.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.628.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.628.0>, #Ref<0.3264398455.2139750403.150894>) at <0.633.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-26 14:59:02.420 [error] <0.627.0> Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.3264398455.2139750403.150893>,opts => [{timeout,15000},{pool_size,nil},{pool,...}],...}) at <0.628.0> exit with reason killed in context child_terminated
2020-08-26 15:00:08.791 [error] <0.488.0> gen_server <0.488.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:08.818 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:08.819 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.1177299713.2945056769.146320>) at <0.488.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:08.819 [error] <0.496.0> gen_server <0.496.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:08.819 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:08.820 [error] <0.487.0> Supervisor {<0.487.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.486.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.486.0>, #Ref<0.1177299713.2945056769.146320>) at <0.496.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:08.820 [error] <0.497.0> gen_server <0.497.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:08.820 [error] <0.497.0> CRASH REPORT Process <0.497.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:49.832 [error] <0.478.0> gen_server <0.478.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:49.852 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:49.853 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.1098111977.1334181889.170690>) at <0.478.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:49.853 [error] <0.486.0> gen_server <0.486.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:49.853 [error] <0.486.0> CRASH REPORT Process <0.486.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:00:49.854 [error] <0.477.0> Supervisor {<0.477.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.476.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.ExchangeApi.Repo'},...], <0.476.0>, #Ref<0.1098111977.1334181889.170690>) at <0.486.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in context child_terminated
2020-08-26 15:00:49.854 [error] <0.487.0> gen_server <0.487.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129
2020-08-26 15:00:49.854 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Postgrex.Protocol':host_and_port/1 line 129 in 'Elixir.Connection':enter_stop/5 line 686
2020-08-26 15:01:45.430 [error] <0.477.0> CRASH REPORT Process <0.477.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>} in 'Elixir.Range':new/2 line 63
2020-08-26 15:01:45.430 [error] <0.476.0>@Elixir.DBConnection.ConnectionPool:init:22 CRASH REPORT Process <0.476.0> with 0 neighbours crashed with reason: no match of right hand value {error,{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>},[{'Elixir.Range',new,2,[{file,"lib/range.ex"},{line,63}]},{'Elixir.DBConnection.ConnectionPool.Pool',init,1,[{file,"lib/db_connection/connection_pool/pool.ex"},{line,18}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},...]},...]}} in 'Elixir.DBConnection.ConnectionPool':init/1 line 22
2020-08-26 15:02:47.635 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>} in 'Elixir.Range':new/2 line 63
2020-08-26 15:02:47.637 [error] <0.485.0>@Elixir.DBConnection.ConnectionPool:init:22 Supervisor 'Elixir.ExchangeApi.Repo' had child 'Elixir.DBConnection.ConnectionPool' started with 'Elixir.Ecto.Repo.Supervisor':start_child({'Elixir.DBConnection.ConnectionPool',start_link,[{'Elixir.Postgrex.Protocol',[{types,'Elixir.Postgrex.DefaultTypes'},...]}]}, 'Elixir.Ecto.Adapters.Postgres', #{cache => #Ref<0.2205629116.2676621313.227754>,opts => [{timeout,15000},{pool_size,<<"10">>},{...}],...}) at undefined exit with reason no match of right hand value {error,{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>},[{'Elixir.Range',new,2,[{file,"lib/range.ex"},{line,63}]},{'Elixir.DBConnection.ConnectionPool.Pool',init,1,[{file,"lib/db_connection/connection_pool/pool.ex"},{line,18}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,301}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,[{file,"gen_server.erl"},...]},...]}} in 'Elixir.DBConnection.ConnectionPool':init/1 line 22 in context start_error
2020-08-26 15:04:09.096 [error] <0.477.0> CRASH REPORT Process <0.477.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"ranges (first..last) expect both sides to be integers, got: 1..\"10\"">>} in 'Elixir.Range':new/2 line 63
2020-08-26 15:05:16.632 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ef14a242-bcb9-41d5-89bb-6e398cee8b24">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...},...}
2020-08-26 15:05:16.654 [error] <0.843.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ef14a242-bcb9-41d5-89bb-6e398cee8b24">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api..."},...]},...]},...},...}
2020-08-26 15:11:16.185 [error] <0.622.0> CRASH REPORT Process <0.622.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"23e4301c-e590-4d63-8b47-f247f4233128">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...},...}
2020-08-26 15:11:16.217 [error] <0.622.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"23e4301c-e590-4d63-8b47-f247f4233128">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api..."},...]},...]},...},...}
2020-08-26 15:12:01.004 [error] <0.624.0> CRASH REPORT Process <0.624.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ebac76e2-6617-4c16-864c-b9e8b8f67b53">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...},...}
2020-08-26 15:12:01.005 [error] <0.624.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"ebac76e2-6617-4c16-864c-b9e8b8f67b53">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api..."},...]},...]},...},...}
2020-08-26 15:14:07.163 [error] <0.680.0> CRASH REPORT Process <0.680.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"b24f959c-6d87-45ba-b401-94d49de9b03b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:14:07.166 [error] <0.680.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"b24f959c-6d87-45ba-b401-94d49de9b03b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:14:52.131 [error] <0.743.0> CRASH REPORT Process <0.743.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"fc036d9f-0616-4e10-a2d6-13f5968b8f2b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:14:52.135 [error] <0.743.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"fc036d9f-0616-4e10-a2d6-13f5968b8f2b">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:15:24.936 [error] <0.802.0> CRASH REPORT Process <0.802.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"8b88647a-3ec1-4b9c-a670-0384fb1462b7">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:15:24.937 [error] <0.802.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"8b88647a-3ec1-4b9c-a670-0384fb1462b7">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:16:13.763 [error] <0.804.0> CRASH REPORT Process <0.804.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:16:13.768 [error] <0.804.0> Cowboy stream 4 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.679.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:18:30.063 [error] <0.864.0> CRASH REPORT Process <0.864.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"ef09f4c2-51fe-4387-beb1-e68a7ef9268c">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...},...}
2020-08-26 15:18:30.063 [error] <0.864.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.863.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"ef09f4c2-51fe-4387-beb1-e68a7ef9268c">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...}
2020-08-26 15:18:48.600 [error] <0.927.0> CRASH REPORT Process <0.927.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"c6a6c0d9-21f2-4d7f-9d1c-f2cfb26a1c6a">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...},...}
2020-08-26 15:18:48.600 [error] <0.927.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.863.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"c6a6c0d9-21f2-4d7f-9d1c-f2cfb26a1c6a">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...}
2020-08-26 15:19:36.232 [error] <0.930.0> CRASH REPORT Process <0.930.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"94823f86-2abd-4f18-83e1-6172df779089">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...},...}
2020-08-26 15:19:36.232 [error] <0.930.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.863.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => uuid,message => nil,term => #{'__struct__' => 'Elixir.Ecto.Changeset',action => nil,changes => #{email => <<"pachedo@bar.com">>,uuid => <<"94823f86-2abd-4f18-83e1-6172df779089">>},constraints => [#{constraint => <<"users_email_index">>,error_message => <<"has already been taken">>,error_type => unique,field => email,match => exact,type => unique}],data => #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',...},...},...}},...},...},...}
2020-08-26 15:24:00.678 [error] <0.1005.0> CRASH REPORT Process <0.1005.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"a12a01dd-de01-460e-8ff0-40400ce007b2">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange..."},...]},...]},...},...},...}
2020-08-26 15:24:00.680 [error] <0.1005.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.987.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"a12a01dd-de01-460e-8ff0-40400ce007b2">>,uuid,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,5}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_a..."},...]},...]},...},...}
2020-08-26 15:24:43.944 [error] <0.1068.0> CRASH REPORT Process <0.1068.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...},...}
2020-08-26 15:24:43.944 [error] <0.1068.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.987.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...}
2020-08-26 15:26:02.620 [error] <0.1128.0> CRASH REPORT Process <0.1128.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-08-26 15:26:02.620 [error] <0.1128.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1127.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-08-26 15:26:37.695 [error] <0.1182.0> CRASH REPORT Process <0.1182.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...},...}
2020-08-26 15:26:37.695 [error] <0.1182.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1127.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...}
2020-08-26 15:27:09.100 [error] <0.1237.0> CRASH REPORT Process <0.1237.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:27:09.100 [error] <0.1237.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1127.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:35:42.904 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 75206,message => nil,postgres => #{code => undefined_table,file => <<"parse_relation.c">>,line => <<"1194">>,message => <<"relation \"users\" does not exist">>,pg_code => <<"42P01">>,position => <<"13">>,routine => <<"parserOpenTable">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"INSERT INTO \"users\" (\"email\",\"inserted_at\",\"updated_at\",\"id\") VALUES ($1,$2,$3,$4)">>},[{'Elixir.Ecto.Adapters.SQL',...},...]},...},...},...}
2020-08-26 15:35:42.941 [error] <0.649.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 75206,message => nil,postgres => #{code => undefined_table,file => <<"parse_relation.c">>,line => <<"1194">>,message => <<"relation \"users\" does not exist">>,pg_code => <<"42P01">>,position => <<"13">>,routine => <<"parserOpenTable">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"INSERT INTO \"users\" (\"email\",\"inserted_at\",\"updated_at\",\"id\") VALUES ($1,$2,$3,$4)">>},[{'Elixir.Ecto.Adapters.SQL',...},...]},...},...}
2020-08-26 15:38:14.667 [error] <0.622.0> CRASH REPORT Process <0.622.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:38:14.675 [error] <0.622.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:40:31.195 [error] <0.641.0> CRASH REPORT Process <0.641.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...},...}
2020-08-26 15:40:31.197 [error] <0.641.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.625.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => {error,reason_for_error}},[{'Elixir.ExchangeApi.Accounts',create_user,1,[{file,"lib/exchange_api/accounts.ex"},{line,58}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,16}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,...},...]},...},...}
2020-08-26 15:41:51.678 [error] <0.701.0> CRASH REPORT Process <0.701.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:41:51.679 [error] <0.701.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.700.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 46,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:42:54.865 [error] <0.761.0> CRASH REPORT Process <0.761.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:42:54.866 [error] <0.761.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 47,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:46:17.136 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 49,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:46:17.159 [error] <0.843.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 49,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
2020-08-26 15:47:17.841 [error] <0.855.0> CRASH REPORT Process <0.855.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Template.UndefinedError',assigns => #{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 50,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"50">>,<<"content-type">> => <<"application/json">>,<<"hos...">> => ...,...},...}},...},...},...},...},...},...},...}
2020-08-26 15:47:17.842 [error] <0.855.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Template.UndefinedError',assigns => #{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 50,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"50">>,<<"content-type">> => <<"application/json">>,<<"host">> => <<..>>,...},...}},...},...},...},...},...},...}
2020-08-26 15:49:04.295 [error] <0.968.0> CRASH REPORT Process <0.968.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 59,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...},...}
2020-08-26 15:49:04.298 [error] <0.968.0> Cowboy stream 5 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.842.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => resp,kind => nil,module => 'Elixir.Plug.Conn'},[{'Elixir.Plug.Conn',resp,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 59,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...],...},...]},...},...}
